### ISSUE TITLE
Broken viewpoint

### ISSUE THREAD

**Issue by ArchBlood** [humhub-contrib/blog#2]
Unable to post more than 1 blog post without the view breaking

![Screenshot_1](https://user-images.githubusercontent.com/35392110/93602258-63037800-f990-11ea-962c-3194b5002918.png)

On a side note I also noticed that `humhub\modules\ui\view\components\View` isn't being used in this module but instead it's using the deprecated `View` components :thinking:

**Comment by buddh4** [comment]
Haven't tested the module for a long time. The deprecated View namespace is probably just used in the `@var` variable description, which is not really a problem, you cannot really use the deprecated class since the new class is defined in the application config and can not be overwritten. Thanks for testing, will check the render bug soon.
